# Generated by Django 3.2.9 on 2021-11-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_class', models.CharField(max_length=200)),
                ('student_dormitory', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='System_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_name', models.CharField(max_length=200)),
                ('users_age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachers_name', models.CharField(max_length=200)),
                ('teachers_date_of_employment', models.DateField()),
                ('teachers_department', models.CharField(max_length=200)),
            ],
        ),
    ]
