# Generated by Django 3.2.9 on 2021-11-24 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='system_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(max_length=200)),
                ('student_class', models.CharField(max_length=200)),
                ('student_dormitory', models.CharField(max_length=200)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.system_user')),
            ],
        ),
    ]
